### ISSUE TITLE
TypeError: headers.forEach is not a function

### ISSUE THREAD

**Issue by visibilityspots** [TehShrike/k#6]
When the columns setting is setted to **all** the ```k tasks``` command isn't working. 

```
$ k set columns "all"
$ k get columns 
all

$ k tasks

/usr/lib/node_modules/kanbanize-cli/task_table.js:14
	headers.forEach(function(bucketName) {
	        ^

TypeError: headers.forEach is not a function
    at new ColumnularTable (/usr/lib/node_modules/kanbanize-cli/task_table.js:14:10)
    at /usr/lib/node_modules/kanbanize-cli/task_table.js:46:15
    at /usr/lib/node_modules/kanbanize-cli/kanbanize_api.js:30:7
    at Request.callback (/usr/lib/node_modules/kanbanize-cli/node_modules/superagent/lib/node/index.js:662:3)
    at Request.<anonymous> (/usr/lib/node_modules/kanbanize-cli/node_modules/superagent/lib/node/index.js:132:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/kanbanize-cli/node_modules/superagent/lib/node/index.js:818:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

When manually configuring the columns it does work.

```
$ k set columns "X,Y,Z"
```

**Comment by rasschaert** [comment]
Same issue, peculiar thing is that it worked _once_ before breaking. Applying the same workaround as @visibilityspots worked.

```
 kenny  pc-1647  ~  k tasks
boardColumns is now Backlog,Requested,In development,Done,Archive
┌─────────┬──────────────────┬───────────────────┬───────────┬─────────┐
│ Backlog │ Requested        │ In development    │ Done      │ Archive │
├─────────┼──────────────────┼───────────────────┼───────────┼─────────┤
│         │ 3618: Deploy foo │ 3603: bar tooling │ 4390: qux │         │
├─────────┼──────────────────┼───────────────────┼───────────┼─────────┤
│         │                  │ 3999: baz porting │           │         │
└─────────┴──────────────────┴───────────────────┴───────────┴─────────┘
 kenny  pc-1647  ~  k tasks
/usr/lib/node_modules/kanbanize-cli/task_table.js:14
    headers.forEach(function(bucketName) {
            ^

TypeError: headers.forEach is not a function
    at new ColumnularTable (/usr/lib/node_modules/kanbanize-cli/task_table.js:14:10)
    at /usr/lib/node_modules/kanbanize-cli/task_table.js:46:15
    at /usr/lib/node_modules/kanbanize-cli/kanbanize_api.js:30:7
    at Request.callback (/usr/lib/node_modules/kanbanize-cli/node_modules/superagent/lib/node/index.js:662:3)
    at Request.<anonymous> (/usr/lib/node_modules/kanbanize-cli/node_modules/superagent/lib/node/index.js:132:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/kanbanize-cli/node_modules/superagent/lib/node/index.js:818:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
 kenny  pc-1647  ~  k get columns                                   1
all
 kenny  pc-1647  ~  k set columns 'Backlog, Requested, In development, Done, Archive'
columns is now Backlog, Requested, In development, Done, Archive
 kenny  pc-1647  ~  k tasks
┌─────────┬──────────────────┬───────────────────┬───────────┬─────────┐
│ Backlog │ Requested        │ In development    │ Done      │ Archive │
├─────────┼──────────────────┼───────────────────┼───────────┼─────────┤
│         │ 3618: Deploy foo │ 3603: bar tooling │ 4390: qux │         │
├─────────┼──────────────────┼───────────────────┼───────────┼─────────┤
│         │                  │ 3999: baz porting │           │         │
└─────────┴──────────────────┴───────────────────┴───────────┴─────────┘
```

**Comment by TehShrike** [comment]
Oh weird!

**Comment by TehShrike** [comment]
Looks like LevelUP dropped the `encoding` property somewhere between the first implementation and when I upgraded for node 4 support..

Fix published as 1.4.1.

**Comment by rasschaert** [comment]
Thanks for looking into this so fast. I'm still having issues with "columns all" in 1.4.1, though now it's a different error:

```
 kenny  pc-1647  ~  sudo npm install --unsafe-perm -g kanbanize-cli                                                                                                                                                                                                          
/usr/bin/k -> /usr/lib/node_modules/kanbanize-cli/index.js

> leveldown@1.4.1 install /usr/lib/node_modules/kanbanize-cli/node_modules/leveldown
> prebuild --download

/usr/lib
└── kanbanize-cli@1.4.1 

 kenny  pc-1647  ~  k set columns all                                                                                                                                                                                                                                        
columns is now all
 kenny  pc-1647  ~  k tasks                                                                                                                                                                                                                                                  
[EncodingError: Unexpected token B]                                                                                                                                                                                                                                     
 kenny  pc-1647  ~  k set columns 'Backlog, Requested, In development, Done, Archive'                                                                                                                                                                                      1 
columns is now Backlog, Requested, In development, Done, Archive
 kenny  pc-1647  ~  k tasks                                                                                                                                                                                                                                                   
┌─────────┬──────────────────┬───────────────────┬───────────┬─────────┐
│ Backlog │ Requested        │ In development    │ Done      │ Archive │
├─────────┼──────────────────┼───────────────────┼───────────┼─────────┤
│         │ 3618: Deploy foo │ 3603: bar tooling │ 4390: qux │         │
├─────────┼──────────────────┼───────────────────┼───────────┼─────────┤
│         │                  │ 3999: baz porting │           │         │
└─────────┴──────────────────┴───────────────────┴───────────┴─────────┘
```

**Comment by TehShrike** [comment]
That seems like the sort of bad state in the local database that might be cleared out if you just try again after doing that `set columns` stuff?

**Comment by rasschaert** [comment]
Playing around with ```set columns``` didn't fix it. I gave up and just deleted ```~/.k/``` and did the ```k set``` song and dance again.

Works like a charm now, thanks.
