### ISSUE TITLE
process.env.HOME is not set on Windows: throws errors

### ISSUE THREAD

**Issue by mnapartovich** [TehShrike/k#8]
Node.js v5.9.0, v4.4.0 LTS
Windows 10

Right after "npm install -g kanbanize-cli":

C:\WINDOWS\system32>k set key "my_key"
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:494:7)
    at Object.<anonymous> (C:\Users\nmark\AppData\Roaming\npm\node_modules\kanbanize-cli\state.js:6:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\nmark\AppData\Roaming\npm\node_modules\kanbanize-cli\kanbanize_api.js:4:13)

**Comment by TehShrike** [comment]
Huh, so this is failing on Windows 10? https://github.com/TehShrike/k/blob/master/state.js#L6

Is `process.env.HOME` not defined on Windows 10?

I don't have WIndows 10 at the moment.  If you fork this library and get it to work on Windows, let me know.

**Comment by mnapartovich** [comment]
Yes, you are right!
Setting HOME is a solution.
Thank you!

**Comment by TehShrike** [comment]
Looks like the fix would be to call [os.homedir()](https://nodejs.org/api/os.html#os_os_homedir).

**Comment by TehShrike** [comment]
Published as 1.4.2
